version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mongodb
        environment:
            MONGO_URI: "mongodb://mongodb:27017/Rescue"
        ports:
            - "8000:8000"

    frontend:
        build:
            context: .
            dockerfile: frontend.Dockerfile
        depends_on:
            - backend
        ports:
            - "3001:3000"

    mongodb:
        image: mongo:6
        container_name: mongo_container
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
