name: Rescue Application build run

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
            AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
            AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
            AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
            APP_BASE_URL: ${{ secrets.APP_BASE_URL }}

        strategy:
            matrix:
                node-version: [22.x]
                python-version: ["3.12", "3.13"]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install `uv`
              run: |
                  curl -LsSf https://astral.sh/uv/install.sh | sh
                  echo "$HOME/.local/bin" >> $GITHUB_PATH

            - name: Install Python dependencies with `uv`
              run: |
                  uv venv .venv
                  source .venv/bin/activate
                  uv sync

            - name: Install Repo dependecies
              run: |
                  npm install --legacy-peer-deps

            - name: Install frontend dependencies
              run: |
                  cd apps/frontend
                  npm install --legacy-peer-deps

            - name: Disable telemetry
              run: |
                  npx turbo telemetry disable
                  npx next telemetry disable

            - name: Run tests
              run: |
                  source .venv/bin/activate
                  npm run build
              env:
                  AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
                  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
                  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
                  APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
